# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- v-next

pool:
  vmImage: 'vs2017-win2016'

steps:
  - task: CosmosDbEmulator@2
    inputs:
      containerName: 'azure-cosmosdb-emulator'
      enableAPI: 'SQL'
      portMapping: '8081:8081, 8901:8901, 8902:8902, 8979:8979, 10250:10250, 10251:10251, 10252:10252, 10253:10253, 10254:10254, 10255:10255, 10256:10256, 10350:10350'
      hostDirectory: '$(Build.BinariesDirectory)\azure-cosmosdb-emulator'
      consistency: 'BoundedStaleness'
  - task: PowerShell@2
    inputs:
      filePath: '.\build\build.ps1'
      arguments: '-Uri $(CosmosDbEmulator.Endpoint)'
      workingDirectory: '$(Build.SourcesDirectory)\build'
