# https://aka.ms/yaml

trigger:
- master

pr:
- master

pool:
  vmImage: windows-2019
stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    steps:
      - task: PowerShell@2
        displayName: 'Starting Cosmos Emulator'
        inputs:
          targetType: 'inline'
          workingDirectory: $(Pipeline.Workspace)
          script: |
            Write-Host "Starting CosmosDB Emulator"
            Import-Module "C:/Program Files/Azure Cosmos DB Emulator/PSModules/Microsoft.Azure.CosmosDB.Emulator"
            Start-CosmosDbEmulator
      - task: PowerShell@2
        displayName: 'Building'
        inputs:
          filePath: '.\build.ps1'
      - task: PublishTestResults@2
        displayName: 'Publish Test Results'
        condition: succeededOrFailed()
        inputs:
          testRunner: VSTest
          testResultsFiles: '**/*.trx'
      - task: CopyFiles@2
        inputs:
          Contents: 'output\*.nupkg'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        displayName: Publish Build Artifacts   
- stage: Publish
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
    - job: Publish
      steps:
        - task: DownloadBuildArtifacts@0
          displayName: 'Download artifacts'
          inputs:
            artifactName: 'drop'
            buildType: 'current'
            downloadType: 'single'
            downloadPath: '$(System.ArtifactsDirectory)'
        - task: NuGetCommand@2
          displayName: Publish package to nuget.org using ASOS organisation account
          inputs:
            command: 'push'
            packagesToPush: '$(System.ArtifactsDirectory)/**/*.nupkg'
            nuGetFeedType: 'external'
            publishFeedCredentials: 'ASOS nuget.org feed'